version: "3"
services:
  twitter_web:
    build: ./web
    container_name: twitter_web
    ports:
      - "32776:80"
    depends_on:
      - twitter_db
    links:
      - twitter_db
    volumes:
      - ./SampleLaravel:/var/www/html
    #restart: always

  twitter_db:
    build: ./db
    container_name: twitter_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: twitter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: "localhost"
    ports:
      - 3306:3306
    expose:
      - 3306
    #restart: always
